# Generated by Django 4.1 on 2022-09-21 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="Sub_type",
        ),
        migrations.RemoveField(
            model_name="account",
            name="disc_id",
        ),
    ]
