# Generated by Django 4.1 on 2022-09-23 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0002_remove_account_sub_type_remove_account_disc_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ship_name", models.CharField(max_length=30)),
                ("fuel", models.BigIntegerField(max_length=20)),
                ("max_fuel", models.BigIntegerField(max_length=20)),
                (
                    "ship_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="login.account"
                    ),
                ),
            ],
        ),
    ]
